name: 'Devcontainer CI'
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-deno-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Run tests in deno-only devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/deno-only/devcontainer.json
          runCmd: deno test

  test-full-build-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run compat tests in full-build-env devcontainer
        uses: devcontainers/ci@v0.3
        with:
          configFile: .devcontainer/full-build-env/devcontainer.json
          runCmd: deno task compat
